Controllers/GameLibraryController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using GameBaseSite.Models;
using GameBaseSite.Models.Quiz;
using System.Diagnostics;
using System.Text.RegularExpressions;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace GameBaseSite.Controllers
{
    public class GameLibraryController : Controller
    {
        private LibraryContext Context { get; set; }

        public GameLibraryController(LibraryContext ctx)
        {
            Context = ctx;
        }

  

        [HttpGet]
        public IActionResult LibraryIndex()
        {
            ViewBag.games = Context.Games.ToList();
            return View();
        }

        [HttpPost]
        public IActionResult LibraryIndex(GameModel model)
        {
            if (model.GameId == 0)
            {
                        
                Context.Games.Add(model);
                Context.SaveChanges();
            }
            else
            {       
                Context.Games.Update(model);
                Context.SaveChanges();
            }

            ViewBag.games = Context.Games.ToList();
            return View(new GameModel());
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            
            GameModel game;
            if (id == 0)
            {

                /*
                int newId = int.Parse(id);
                newId++;
                string stringId = newId.ToString();
                id = stringId;
                game = Context.Games.Add(id);
                ViewBag.button = "Add";
                */
                ViewBag.button = "Add";
                game = new GameModel();
                return View(game);
            }
            else
            {
                game = Context.Games.Find(id);
                ViewBag.button = "Save";
                return View(game);
            }
       
        }

        [HttpGet]
        public IActionResult Remove(int id)
        {
            GameModel game = Context.Games.Find(id);
            Context.Games.Remove(game);
            Context.SaveChanges();

            ViewBag.games = Context.Games.ToList();
            return View("LibraryIndex");
        }

        [HttpPost]
        public IActionResult Search(GameModel model)
        {
            ViewBag.games = Context.Games.Where(g => g.Title.Contains(model.Title)).ToList();
            return View();
        }

         /*
        public string GameIdIncrement(GameModel game)
        {
           var gameList = Context.Games.ToList();
           string length = gameList.Count.ToString();
           var lastGame = gameList.Where(x => x.GameId == length);
           string idString = lastGame.ToString();
        }
         */
    

    }
}

Controllers/Profile/CompareController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using GameBaseSite.Models;
using GameBaseSite.Models.Database;



namespace GameBaseSite.Controllers
{
    public class CompareController : Controller
    {
        private LibraryContext Context;
        public CompareController(LibraryContext ctx)
        {
            Context = ctx;
        }
        [HttpGet]
        public IActionResult CompareIndex()
        {
            return View();
        }

      
        [HttpPost]
        public IActionResult CompareResult(Search s)
        {
            List<string> results = new List<string>();
            List<string> results2 = new List<string>();
            List<string> common = new List<string>();

            var users = Context.User.Where(u => u.UserId == s.Query).ToList();
            foreach(UserModel u in users)
            {
                //results.Add(u.UserId);
            }

            var usrGames = from u in Context.User
                           join uG in Context.UsrGames on u.UserId equals uG.UserId
                           where u.UserId.Equals(s.Query)
                           select uG.Title;
            foreach(string x in usrGames)
            {
                results.Add(x);
            }

            var users2 = Context.User.Where(u2 => u2.UserId == s.Query2).ToList();
            foreach (UserModel u2 in users)
            {
                //results2.Add(u2.UserId);
            }

            var usrGames2 = from u2 in Context.User
                           join uG2 in Context.UsrGames on u2.UserId equals uG2.UserId
                            where u2.UserId.Equals(s.Query2)
                            select uG2.Title;
            foreach (string x in usrGames2)
            {
                results2.Add(x);
            }

            foreach(var game in results)
            {
                if (results2.Contains(game))
                    common.Add(game);
            }

            if (common.Count() == 0)
            {
                string msg = "You don't share any games :(";
                common.Add(msg);
            }

            ViewBag.results = results;
            ViewBag.results2 = results2;
            ViewBag.common = common;
            return View();
        }
    }
}

Controllers/QuizController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using GameBaseSite.Models;
using System.Diagnostics;
using GameBaseSite.Models.Quiz;

namespace GameBaseSite.Controllers
{
    public class QuizController : Controller
    {
        private LibraryContext Context { get; set; }

        public QuizController(LibraryContext ctx)
        {
            Context = ctx;
        }


        [HttpGet]
       public IActionResult QuizIndex()
        {
            ViewBag.powerScore = 0;
            ViewBag.casualScore = 0;
            ViewBag.oldschoolScore = 0;
            ViewBag.brainyScore = 0;
            ViewBag.questionId = 1;

            Question q = QuestionDB.GetQuestion(ViewBag.questionId);
            ViewBag.QuestionText = q.QText;
            ViewBag.AnswerPText = q.AnsPower;
            ViewBag.AnswerCText = q.AnsCasual;
            ViewBag.AnswerOText = q.AnsOld;
            ViewBag.AnswerBText = q.AnsBrainy;

            return View();
        }

        [HttpPost]
        public IActionResult QuizIndex(QuizState inModel, GameModel game)
        {
            ViewBag.powerScore = inModel.powerScore;
            ViewBag.casualScore = inModel.casualScore;
            ViewBag.oldschoolScore = inModel.oldschoolScore;
            ViewBag.brainyScore = inModel.brainyScore;
            ViewBag.questionId = inModel.questionId + 1;

            if (inModel.Answer == "A") { ViewBag.powerScore++; }
            if (inModel.Answer == "B") { ViewBag.casualScore++; }
            if (inModel.Answer == "C") { ViewBag.oldschoolScore++; }
            if (inModel.Answer == "D") { ViewBag.brainyScore++; }

            Question q = QuestionDB.GetQuestion(ViewBag.questionId);
            ViewBag.QuestionText = q.QText;
            ViewBag.AnswerPText = q.AnsPower;
            ViewBag.AnswerCText = q.AnsCasual;
            ViewBag.AnswerOText = q.AnsOld;
            ViewBag.AnswerBText = q.AnsBrainy;

            ModelState.Clear();

            if(ViewBag.questionId > 10)
            {
                

                var typeTemp = inModel.getType();
                ViewBag.Type = typeTemp;
                ViewBag.games = Context.Games.Where(g => g.Type.Contains(typeTemp)).ToList();

                return View("GamerType");
            }

            return View();
        }


      
    }
}

Views/Shared/ProfileIndex.cshtml
@model GameModel
@{
    ViewData["Title"] = "Profile";
}

<h1>Profile</h1>
<p>Test test test </p>

<div class="container">

    <h2>Username's Profile <!--Change this to a specific username later--></h2>
    <h3>UserID <!--Change this to a user ID later--></h3>


    <table border="1" style="border-collapse: collapse; width: 100%; height: 105px;">
        <thead>
            <tr style="height: 21px;">
                <th style="width: 10%; height: 21px;">Title</th>
                <th style="width: 10%; height: 21px;">Genre</th>
                <th style="width: 10%; height: 21px;">ESRB</th>         
                <th style="width: 10%; height: 21px;">Edit</th>
                <th style="width: 10%; height: 21px;">Remove</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var game in ViewBag.Games)
            {
            <tr style="height: 21px;">
                <td style="width: 10%; height: 21px;">@game.Title</td>
                <td style="width: 10%; height: 21px;">@game.Genre</td>
                <td style="width: 10%; height: 21px;">@game.EsrbRating</td>
                <td style="width: 10%; height: 21px;"><a asp-controller="Profile" asp-action="Edit" asp-route-id="@game.GameId">Edit</a></td>
                <td style="width: 10%; height: 21px;"><a asp-controller="Profile" asp-action="Remove" asp-route-id="@game.GameId">Remove</a></td>
            </tr>
            }
        </tbody>
    </table>
    <a class="nav-link" asp-area="" asp-controller="GameLibrary" asp-action="Edit" asp-route-id="0">Click here to add a game to your list</a>

</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <title>@ViewData["Title"] - GameBaseSite</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/style.css" />
    <style>
        figure table {
            border-collapse: collapse;
        }

        table,
        th,
        td {
            border: 1px solid black;
            text-align: center;
        }

        th {
            width: 20%;
        }

        section,
        article {
            text-align: center;
            border-style: ridge;
        }
    </style>
</head>

<body>
    <header>

        <h1 style="font-size: xx-large;font-weight: bold;text-align: center;">
            GAME BASE
            <ul>
                <li>|| <a asp-area="" asp-controller="Home" asp-action="Index">HOME</a> || </li>
                <li>|| <a asp-area="" asp-controller="GameLibrary" asp-action="LibraryIndex">GAME LIBRARY</a> || </li>
                <li>|| <a asp-area="" asp-controller="Profile" asp-action="ProfileIndex">PROFILE</a> || </li>
                <li>|| <a asp-area="" asp-controller="Quiz" asp-action="QuizIndex">GAMER TYPE QUIZ</a> || </li>
                <li>|| <a asp-area="" asp-controller="Compare" asp-action="CompareIndex">COMPARE</a> || </li>
            </ul>
        </h1>

    </header>

    <div class="layer">
        <section>
            
                <main role="main">
                    <section>
                        @RenderBody()
                    </section>
                </main>
            
        </section>


    </div>


    <br>
    <footer>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>