Controllers/GameLibraryController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using GameBaseSite.Models;
using GameBaseSite.Models.Quiz;
using System.Diagnostics;
using System.Text.RegularExpressions;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace GameBaseSite.Controllers
{
    public class GameLibraryController : Controller
    {
        private LibraryContext Context { get; set; }

        public GameLibraryController(LibraryContext ctx)
        {
            Context = ctx;
        }

  

        [HttpGet]
        public IActionResult LibraryIndex()
        {
            ViewBag.games = Context.Games.ToList();
            return View();
        }

        [HttpPost]
        public IActionResult LibraryIndex(GameModel model)
        {
            if (model.GameId == 0)
            {
                        
                Context.Games.Add(model);
                Context.SaveChanges();
            }
            else
            {       
                Context.Games.Update(model);
                Context.SaveChanges();
            }

            ViewBag.games = Context.Games.ToList();
            return View(new GameModel());
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            
            GameModel game;
            if (id == 0)
            {

                /*
                int newId = int.Parse(id);
                newId++;
                string stringId = newId.ToString();
                id = stringId;
                game = Context.Games.Add(id);
                ViewBag.button = "Add";
                */
                ViewBag.button = "Add";
                game = new GameModel();
                return View(game);
            }
            else
            {
                game = Context.Games.Find(id);
                ViewBag.button = "Save";
                return View(game);
            }
       
        }

        [HttpGet]
        public IActionResult Remove(int id)
        {
            GameModel game = Context.Games.Find(id);
            Context.Games.Remove(game);
            Context.SaveChanges();

            ViewBag.games = Context.Games.ToList();
            return View("LibraryIndex");
        }

        [HttpPost]
        public IActionResult Search(GameModel model)
        {
            ViewBag.games = Context.Games.Where(g => g.Title.Contains(model.Title)).ToList();
            return View();
        }

         /*
        public string GameIdIncrement(GameModel game)
        {
           var gameList = Context.Games.ToList();
           string length = gameList.Count.ToString();
           var lastGame = gameList.Where(x => x.GameId == length);
           string idString = lastGame.ToString();
        }
         */
    

    }
}

Controllers/Profile/ProfileController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

using GameBaseSite.Models;
using System.Diagnostics;

namespace GameBaseSite.Controllers
{
    public class ProfileController : Controller
    {

        private LibraryContext Context { get; set; }

        public ProfileController(LibraryContext ctx)
        {
            Context = ctx;
        }

        [HttpGet]
        public IActionResult ProfileIndex()
        {
           
            ViewBag.games = Context.ProfileGames.ToList();
            return View();
        }

        [HttpGet]
        public IActionResult Remove(string id)
        {
            ProfileGameModel game = Context.ProfileGames.Find(id);
            Context.ProfileGames.Remove(game);
            Context.SaveChanges();

            ViewBag.games = Context.Games.ToList();
            return View("LibraryIndex");
        }


        [HttpGet]
        public IActionResult Edit(string id)
        {
            ProfileGameModel game;
            if (String.IsNullOrEmpty(id))
            {
                game = Context.ProfileGames.Find(id);
                ViewBag.button = "Save";
                return View(game);
            }
            else
            {
                game = Context.ProfileGames.Find(id);
                ViewBag.button = "Save";
                return View(game);
            }

        }






        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/extraViews/bLayout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <title>@ViewData["Title"] - GameBaseSite</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/style.css" />
    <style>
        figure table {
            border-collapse: collapse;
        }

        table,
        th,
        td {
            border: 1px solid black;
            text-align: center;
        }

        th {
            width: 20%;
        }

        section,
        article {
            text-align: center;
            border-style: ridge;
        }
    </style>
</head>

<body>
    <header>

        <h1 style="font-size: xx-large;font-weight: bold;text-align: center;">
            GAME BASE
            <ul>
                <li>|| <a asp-area="" asp-controller="Home" asp-action="Index">HOME</a> || </li>
                <li>|| <a asp-area="" asp-controller="GameLibrary" asp-action="LibraryIndex">GAME LIBRARY</a> || </li>
                <li>|| <a asp-area="" asp-controller="Profile" asp-action="ProfileIndex">PROFILE</a> || </li>
                <li>|| <a asp-area="" asp-controller="CompareController" asp-action="CompareIdex">COMPARE</a> || </li>
            </ul>
        </h1>

    </header>

    <div class="layer">
        <section>
            <h2> Welcome to the G A M E  Z O N E</h2>
            <figure>
                <figcaption>
                    A ZONE FOR GAMES. ADD YOUR GAMES TO OUR LIBRARY, AND YOUR PERSONAL COLLECTION.<br />
                    YOU CAN ALSO COMPARE YOUR COLLECTION WITH OTHER USER'S.
                </figcaption>
            </figure>
        </section>


    </div>


    <br>
    <footer>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

Views/extraViews/copy_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - GameBaseSite</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-gray border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">GAME BASE</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">HOME</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="GameLibrary" asp-action="LibraryIndex">GAME LIBRARY</a>
                        </li>
                        <li class="nav-item">
                            <!--profile link-->
                            <a class="nav-link text-dark" asp-area="" asp-controller="Profile" asp-action="ProfileIndex">PROFILE</a>
                        </li>
                        <li class="nav-item">
                            <!--compare link-->
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <section class="container">
        <main role="main">
            <section>
                @RenderBody()
            </section>
        </main>
    </section>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - GameBaseSite - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>